spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver





security:
  jwt:
    secret: ZmFkc2hqZ2JicWprd2NleGhycWtqZWh3eGh2cXdoeGp2Z2p5aHJncWV4aGplZ2hqeHF2YmhqZXh2cmhqcWtndndieGhqcnF3ZXhy
    access: 3600000
    refresh: 2592000000



