spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?/currentSchema=tasklist
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:demo_data.sql