spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_list
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

